language: c
os: linux
dist: xenial
sudo: false

before_install:
  - echo "Testing Hello_world"
  - cmake -E remove_directory build
  - cmake -E remove_directory bin

install:
- mkdir build
- cd build
- cmake .. -DCMAKE_BUILD_TYPE=Release

script:
  - cmake --build .

after_success:
  - cd $TRAVIS_BUILD_DIR
  - ./hello_world_c
  - echo "Test Success - Branch($TRAVIS_BRANCH)"

notifications:
  email: false

