
matrix:
  include:
    - name: "Build Release C"
      language: c
      install:
        - mkdir -p build && cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_C=ON
        - cmake --build . --config Release
      script:
        - cd $TRAVIS_BUILD_DIR/bin
        - ./hello_world_c
    - name: "Build Release CPP"
      language: cpp
      install:
        - mkdir -p build && cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_CPP=ON
        - cmake --build . --config Release
      script:
        - cd $TRAVIS_BUILD_DIR/bin
        - ./hello_world_cpp
    - name: "Build Debug C"
      language: c
      install:
        - mkdir -p build && cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_C=ON
        - cmake --build . --config Debug
      script:
        - cd $TRAVIS_BUILD_DIR/bin
        - ./hello_world_cd
    - name: "Build Debug CPP"
      language: cpp
      install:
        - mkdir -p build && cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_CPP=ON
        - cmake --build . --config Debug
      script:
        - cd $TRAVIS_BUILD_DIR/bin
        - ./hello_world_cppd
    - name: "Build Debug CPP and Code Coverage"
      language: cpp
      sudo: true
      addons:
        apt:
          packages: lcov
      install:
        - mkdir -p build && cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_CPP=ON -DCODE_COVERAGE=ON
        - cmake --build . --config Debug
      script:
        - cd $TRAVIS_BUILD_DIR/bin
        - ./hello_world_cppd
      after_success:
        - cd $TRAVIS_BUILD_DIR/build
        - lcov --directory . --capture --output-file coverage.info
        - bash <(curl -s https://codecov.io/bash) -f coverage.info
    - name: "Build Release JAVA"
      language: java
      install:
        - mkdir -p build && cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_JAVA=ON
        - cmake --build .
      script:
        - cd $TRAVIS_BUILD_DIR/bin
        - java -cp hello_world_java.jar hello_world_java
    - name: "Build Release PYTHON 2.7"
      language: python
      python:
        - "2.7"
      install:
        - cd $TRAVIS_BUILD_DIR/src/src_python
        - pip install -r requirements.txt
      script:
        - python hello_world_python.py
    - name: "Build Release PYTHON 3.5"
      language: python
      python:
        - "3.5"
      install:
        - cd $TRAVIS_BUILD_DIR/src/src_python
        - pip install -r requirements.txt
      script:
        - python hello_world_python.py

os: linux
dist: xenial
sudo: false
addons:
  apt:
    packages: lcov

before_install:
  - echo "Testing Hello_world"
  - cmake -E remove_directory build
  - cmake -E remove_directory bin

after_success:
  - echo "Test Success - Branch($TRAVIS_BRANCH)"

notifications:
  email: false
