
matrix:
  include:
    - language: c
      before_script:
        - cd backend/tests
      script:
        - cd $TRAVIS_BUILD_DIR/bin
        - ./hello_world_c

    - language: c++
      script:
        - cd $TRAVIS_BUILD_DIR/bin
        - ./hello_world_cpp


os: linux
dist: xenial
sudo: false

before_install:
  - echo "Testing Hello_world"
  - cmake -E remove_directory build
  - cmake -E remove_directory bin

install:
- mkdir build
- cd build
- cmake .. -DCMAKE_BUILD_TYPE=Release
- cmake --build .

after_success:
  - echo "Test Success - Branch($TRAVIS_BRANCH)"

notifications:
  email: false
