matrix:
  include:
    - name: "Build Release C"
      language: c
      install:
        - mkdir -p $TRAVIS_BUILD_DIR/build && cd $TRAVIS_BUILD_DIR/build
        - cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_C=ON
        - cmake --build . --config Release
      script:
        - cd $TRAVIS_BUILD_DIR/bin
        - ./hello_world_c
    - name: "Build Release CPP"
      language: cpp
      install:
        - mkdir -p $TRAVIS_BUILD_DIR/build && cd $TRAVIS_BUILD_DIR/build
        - cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_CPP=ON
        - cmake --build . --config Release
      script:
        - cd $TRAVIS_BUILD_DIR/bin
        - ./hello_world_cpp
    - name: "Build Debug C"
      language: c
      install:
        - mkdir -p $TRAVIS_BUILD_DIR/build && cd $TRAVIS_BUILD_DIR/build
        - cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_C=ON
        - cmake --build . --config Debug
      script:
        - cd $TRAVIS_BUILD_DIR/bin
        - ./hello_world_cd
    - name: "Build Debug C and Code Coverage"
      language: c
      sudo: true
      addons:
        apt:
          packages:
            - lcov
      install:
        - mkdir -p $TRAVIS_BUILD_DIR/build && cd $TRAVIS_BUILD_DIR/build
        - cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_C=ON -DCODE_COVERAGE=ON
        - cmake --build . --config Debug
      script:
        - cd $TRAVIS_BUILD_DIR/bin
        - ./hello_world_cd
      after_success:
        - cd $TRAVIS_BUILD_DIR/build
        - lcov --directory . --capture --output-file coverage_c.info
        - bash <(curl -s https://codecov.io/bash) -f coverage_c.info
        - echo "Test Success - Branch($TRAVIS_BRANCH)"
    - name: "Build Debug CPP"
      language: cpp
      install:
        - mkdir -p $TRAVIS_BUILD_DIR/build && cd $TRAVIS_BUILD_DIR/build
        - cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_CPP=ON
        - cmake --build . --config Debug
      script:
        - cd $TRAVIS_BUILD_DIR/bin
        - ./hello_world_cppd
    - name: "Build Debug CPP and Code Coverage"
      language: cpp
      sudo: true
      addons:
        apt:
          packages:
            - lcov
      install:
        - mkdir -p $TRAVIS_BUILD_DIR/build && cd $TRAVIS_BUILD_DIR/build
        - cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_CPP=ON -DCODE_COVERAGE=ON
        - cmake --build . --config Debug
      script:
        - cd $TRAVIS_BUILD_DIR/bin
        - ./hello_world_cppd
      after_success:
        - cd $TRAVIS_BUILD_DIR/build
        - lcov --directory . --capture --output-file coverage_cpp.info
        - bash <(curl -s https://codecov.io/bash) -f coverage_cpp.info
        - echo "Test Success - Branch($TRAVIS_BRANCH)"
    - name: "Build JAVA"
      language: java
      install:
        - gradle build
      script:
        - gradle run
    - name: "Build JAVA and Code Coverage"
      language: java
      install:
        - gradle build
      script:
        - gradle run
      after_success:
        - gradle codeCoverageReport
        - cd $TRAVIS_BUILD_DIR/build/
        - bash <(curl -s https://codecov.io/bash)
        - cd $TRAVIS_BUILD_DIR/build/report/
        - bash <(curl -s https://codecov.io/bash)
        - echo "Test Success - Branch($TRAVIS_BRANCH)"
    - name: "Build Release PYTHON 2.7"
      language: python
      python:
        - "2.7"
      install:
        - cd $TRAVIS_BUILD_DIR/src/src_python
        - pip install -r requirements.txt
      script:
        - python hello_world_python.py
    - name: "Build Release PYTHON 3.5"
      language: python
      python:
        - "3.5"
      install:
        - cd $TRAVIS_BUILD_DIR/src/src_python
        - pip install -r requirements.txt
      script:
        - python hello_world_python.py

os: linux
dist: xenial
sudo: false

before_install:
  - echo "Testing Hello_world"
  - rm -rf $TRAVIS_BUILD_DIR/build $TRAVIS_BUILD_DIR/bin

after_success:
  - echo "Test Success - Branch($TRAVIS_BRANCH)"

notifications:
  email: false
