language: c
os: linux
dist: xenial
sudo: false

before_install:
  - echo "Testing Hello_world"

install:
- mkdir build
- cd build
- cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON

script: cmake --build .

after_success:
  - ./hello_world
  - echo "Test Success - Branch($TRAVIS_BRANCH)"

notifications:
  email: false

