
matrix:
  include:
    - name: "Build release C"
      language: c
      install:
        - mkdir -p build
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_C=ON
        - cmake --build .
      script:
        - cd $TRAVIS_BUILD_DIR/bin
        - ./hello_world_c
    - name: "Build release CPP"
      language: cpp
      install:
        - mkdir -p build
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_CPP=ON
        - cmake --build .
      script:
        - cd $TRAVIS_BUILD_DIR/bin
        - ./hello_world_cpp
    - name: "Build release JAVA"
      language: java
      install:
        - mkdir -p build
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_JAVA=ON
        - cmake --build .
      script:
        - cd $TRAVIS_BUILD_DIR/bin
        - java -cp hello_world_java.jar hello_world_java
    - name: "Build release PYTHON 2.7"
      language: python
      python:
        - "2.7"
      install:
        - cd $TRAVIS_BUILD_DIR/src/src_python
        - pip install -r requirements.txt
      script:
        - python hello_world_python.py
    - name: "Build release PYTHON 3.5"
      language: python
      python:
        - "3.5"
      install:
        - cd $TRAVIS_BUILD_DIR/src/src_python
        - pip install -r requirements.txt
      script:
        - python hello_world_python.py

os: linux
dist: xenial
sudo: false

before_install:
  - echo "Testing Hello_world"
  - cmake -E remove_directory build
  - cmake -E remove_directory bin

after_success:
  - echo "Test Success - Branch($TRAVIS_BRANCH)"

notifications:
  email: false
